name: chayil
description: "Official Chayil Martial Arts app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  json_annotation: ^4.8.0
  flutter_secure_storage: ^9.0.0
  chewie: ^1.7.4
  smartlogger: ^1.1.4+1
  video_player: ^2.8.2
  device_info_plus: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
  assets:
    - assets/data/categories.json.enc
    - assets/data/ranks.json.enc
    - assets/data/techniques.json.enc
    - assets/images/logo.png
    - assets/images/fist.png
    - assets/images/tab-belt.png
    - assets/images/tab-category.png
