name: chayil
description: "Official Chayil Martial Arts app."
publish_to: 'none'

version: 1.0.0+46

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  json_annotation: ^4.8.0
  flutter_secure_storage: ^10.0.0-beta.4
  shared_preferences: ^2.2.2
  chewie: ^1.7.4
  smartlogger: ^1.1.4+1
  video_player: ^2.8.2
  device_info_plus: ^11.3.3
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  flutter_lints: ^5.0.0 

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
  assets:
    - assets/data/categories.json
    - assets/data/ranks.json
    - assets/data/techniques.json
    - assets/images/logo.png
    - assets/images/fist.png
    - assets/images/tab-belt.png
    - assets/images/tab-category.png
    - assets/images/tab-fist.png
    - assets/images/white_belt.png
    - assets/images/yellow_belt.png
    - assets/images/orange_belt.png
    - assets/images/green_belt.png
    - assets/images/blue_belt.png
    - assets/images/purple_belt.png
    - assets/images/brown_belt.png
    - assets/images/red_belt.png
    - assets/images/red_black_belt.png
    - assets/images/black_white_belt.png
    - assets/images/1st_dan_belt.png
    - assets/images/2nd_dan_belt.png